=== miguel16ra/Globbe-Fitness-MiguelAngel-Restrepo-Ayala/Lenguaje de Marcas/XML/reservas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="globbeFitness">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reservas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="reserva" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fechaReserva" type="xs:date"/>
                                        <xs:element name="estado">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="confirmada"/>
                                                    <xs:enumeration value="cancelada"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="asistencia" type="xs:boolean"/>
                                        <xs:element name="socio">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="apellidos" type="xs:string"/>
                                                    <xs:element name="dni">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[0-9]{8}[A-Z]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="email" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="idSocio" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:int">
                                                            <xs:minInclusive value="1"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="clase">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="fecha" type="xs:date"/>
                                                    <xs:element name="hora" type="xs:string"/>
                                                    <xs:element name="sala" type="xs:string"/>
                                                    <xs:element name="monitor" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="idClase" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:int">
                                                            <xs:minInclusive value="1"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:int">
                                                <xs:minInclusive value="1"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguel16ra/Globbe-Fitness-MiguelAngel-Restrepo-Ayala/Lenguaje de Marcas/XML/reservas.xml
<?xml version="1.0" encoding="UTF-8"?>
<globbeFitness xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="reservas.xsd">
    <reservas>
        <reserva id="1">
            <fechaReserva>2026-04-15</fechaReserva>
            <estado>confirmada</estado>
            <asistencia>true</asistencia>
            <socio idSocio="1">
                <nombre>Miguel Angel</nombre>
                <apellidos>Restrepo Ayala</apellidos>
                <dni>12345678A</dni>
                <email>miguel@gmail.com</email>
            </socio>
            <clase idClase="1">
                <nombre>Spinning</nombre>
                <fecha>2026-04-20</fecha>
                <hora>18:00:00</hora>
                <sala>Sala 1</sala>
                <monitor>Alba Ruiz</monitor>
            </clase>
        </reserva>
        <reserva id="2">
            <fechaReserva>2026-04-15</fechaReserva>
            <estado>confirmada</estado>
            <asistencia>false</asistencia>
            <socio idSocio="2">
                <nombre>Olga</nombre>
                <apellidos>Moreno Martin</apellidos>
                <dni>23456789B</dni>
                <email>olga@gmail.com</email>
            </socio>
            <clase idClase="2">
                <nombre>Yoga</nombre>
                <fecha>2026-04-21</fecha>
                <hora>10:00:00</hora>
                <sala>Sala 2</sala>
                <monitor>Lucia Maria</monitor>
            </clase>
        </reserva>
    </reservas>
</globbeFitness>

=== miguel16ra/Globbe-Fitness-MiguelAngel-Restrepo-Ayala/Lenguaje de Marcas/XML/reservas_invalido.xml
<?xml version="1.0" encoding="UTF-8"?>
<globbeFitness xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="reservas.xsd">
    <reservas>
        <reserva id="1">
            <fechaReserva>2026-04-15</fechaReserva>
            <estado>pendiente</estado>
            <asistencia>true</asistencia>
            <socio idSocio="1">
                <nombre>Miguel Angel</nombre>
                <apellidos>Restrepo Ayala</apellidos>
                <dni>12345678A</dni>
                <email>miguel@gmail.com</email>
            </socio>
            <clase idClase="1">
                <nombre>Spinning</nombre>
                <fecha>2026-04-20</fecha>
                <hora>18:00:00</hora>
                <sala>Sala 1</sala>
                <monitor>Alba Ruiz</monitor>
            </clase>
        </reserva>
    </reservas>
</globbeFitness>
